project:
  type: website
  output-dir: docs

website:
  title: "Home"
  navbar:
    right:
      - icon: github
        text: Github
        href: https://github.com/sbnguah/
      - icon: twitter
        text: Twitter
        href: https://twitter.com/sbnguah/
      - icon: link
        text: Website
        href: https://sbnguah.netlify.app
format:
  html:
    theme: cerulean
    css:   styles.css

editor: visual

