---
title: "Data Description"
author: "Samuel Blay Nguah"
date: "2024-02-15"
categories: [Other]
---

This post describes the data set to be used in the workshop.

## ANCData

**Description**  
This dataset can be downloaded from [here](ANCData.xls). It contains records of high-risk pregnant women under a trial on new and old methods of antenatal care in two clinics. The outcome was perinatal mortality. There are 755 observations with the following 3 variables.

-   **death**: A categorical variable indicating if death occurred in the infant.
-   **anc**: Indicates which type of ANC method was used.
-   **clinic**: Indicates which clinic the patient was seen at.

## blood

**Description**  
This dataset can be downloaded from [here](blood.xlsx). It contains records of  cross-sectional study of the blood reseult of 50 children. It has the following 3 variables.

-   **stno**: The study ID.
-   **age**: Age in completed months of the study participants.
-   **wgt**: Weight in kilogram
-   **hgt**: Height in cms
-   **hb**: Blood hemoglobin concentration in g/dL
-   **wbc**: White blood cell count
-   **hct**: Blood hematocrit in %



